sudo: required
dist: trusty
language: node_js
node_js:
- node
before_script:
- npm install
script:
- npm test
deploy:
  app: jukebox-music
  provider: heroku
  api_key:
    secure: eFKGovT81kS4jP3hEk+Kk6V8c3V/2dee3oDT0CtrKT1QoHaDZ9nBczXQOtlTjWVPq0wiJ2KDzyMj7C1I8mpdhnxuBRgAnLsv7hDe9yqD7C20ZLyLFqqWwjogUF0EeB1PRt0w8f/aC0yvk8aPJ7dm3k6iPoEUc/8w7dm5zUc7G0/fZDPw2WXVdo+FeXvoYzw4plI3I0T50P7yIM2+XYWV8aMBZKcVjlk9czpYYAIYsorhkjl8XbzozAT08Gr8IpJkzt4MbhIDDtcB96OlV78qYVTZSRCHes7Rna5u2Pn5PYeVkt9D6fQqSXzjVyGmUrfoW59jtJK+MEB0/Eauo3w2RtZ8mxlshAJu89z7EhdAaZGquO+hc9ST5N2QuQkB2EZ/UMtVI8+n73h313ybH0RQDspPzt81hnJN49HhtfKGMmZ9oCRQ2I/3DtFrTObQ45N7GUU1xh3TEdwwC/VaCcqhqS5f2htRAvUSMRWjhuxBmbMfK7yn8AswL5P3OZP/5GIcGdz75u97VbEaRiw3b2oKrrdMK/RRe214sPueEKPOHMnxuiu996UCRce1JvbalnpUJCSvVbeA3IxvzTXCxqFWRTKJ20TyEQSQ7ep7yKaWuWJkHPIneVRLNRxwxBQH+mTkKpEC37Mo/OxFT6XBoDQ5jyK/dRKORGRjIh0kEn0NJgk=
