sudo: required
dist: trusty
language: node_js
node_js:
- node
before_script:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: CYt9tgiemyDBUVlOrte1ekHZawz8tIcvJayavzCefqbWb1kE6cox0LnaZ2loUJDtYowHqmtfKkWCGdPIADeAlNt9I6tV1UyKYgBla0vmCdBeNEk/1eOkoKZxu3hjLtgh7I+a7zf+GgVQXgE8TDJMyrUfT12fIy38xIziGkoFWhdsp0zUu2V4t1ZTD7DEKzhfA4KV+ipGBec8T9LguyYanfEENlF0c5r9r+kQ09dSXqaWdt03X1nyBzsfvloQZ3kDBaMahnMQExPw9ESi9ihivZdUFm+8Ttc9rv/u4Z5DGWqYEz6Zgsljcg6jmEJijhz9CYmAzxmGftDd69UrlqOPHq44QCdbkwvRDuFgoPqsDNFzGyB57kAX0yNIHpWOtddvvaXmwNKCa807dkIJl2KvkfJIjfzKa2qQnRCoR09tcJAt/ACTYezvj8nyTx/ozS6phgFZmwCO65Y1sOYU57xhLDT2r2pRWwN5uTaFL0maXFtjY6kV/28IXrjxeKgzlaPQbnFiY+S9Q4Wg6uhs/ILOnXGaCTzRVq5Z+ji8KQDPuivNJrtFtcKPTwWebgXtnz+BIhLp2SpN4hk1h2p1qKC0dnW1wG8QB9PLmmDN/ADwUEau0gvHjx2CNEGtwe6o96EZ6pySJmOtN77G0KEGv03B8PBsBA72UEftch4aJXlLAEk=
  app: jukebox-music
  on:
    repo: Jukebox-Music/Jukebox-Server
